"""Initial migration

Revision ID: 708b81e59d2a
Revises: 
Create Date: 2024-11-20 01:59:01.051337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708b81e59d2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
